### ISSUE TITLE
"Active Devices" metric likely to confuse most people

### ISSUE THREAD

**Issue by PharkMillups** [helium/network-explorer#31]
Currently new explorer shows "Active Devices" for both IOT and Mobile. To most people a "device" is going to be interpreted as an end device that uses the network, versus a Hotspot / Radio that is providing coverage. This will lead to significant confusion. Language should be updated to reflect that this metric is related to hardware providing coverage, not usage.

**Comment by mbthiery** [comment]
Updated to "Active Hotspots"
