### ISSUE TITLE
Typo in label

### ISSUE THREAD

**Issue by jthiller** [helium/network-explorer#32]
Quick one:
https://discord.com/channels/404106811252408320/748320367176581200/1098338756358049862
![image](https://user-images.githubusercontent.com/1965053/233196129-1fb5d3bb-dbd1-41f2-b852-40fd783502d9.png)

**Comment by mdaviesnz** [comment]
I'm helping! 
https://github.com/helium/network-explorer/pull/33

**Comment by jthiller** [comment]
Closed by #33
